### PR TITLE
fix some baronies in the wrong province histories

### PR DESCRIPTION
**Pull request by questionmarkexclamationpoint**

### CODE REVIEW

**Comment by questionmarkexclamationpoint** [comment]
Some of these are vanilla issues, and some are the result of copying old plus files for history.

**Comment by questionmarkexclamationpoint** [comment]
Wait to merge this. I'm gonna check on some of these.

**Comment by schwarherz** [comment]
> Wait to merge this. I'm gonna check on some of these.

Roger that. I'll avoid even reviewing it until then

**Comment by questionmarkexclamationpoint** [comment]
Closing this and deleting, since I'm working on this stuff in another branch now.

**Pull request closed without merging**
