### PR TITLE
removed expensive any_character

### PR DESCRIPTION
**Pull request by schwarherz**
in favor of the lighter CPU use `any_independent ruler = { any_realm_character = { } }`

### CODE REVIEW

**Comment by questionmarkexclamationpoint** [comment]
How is this not ultimately doing the same thing? One iterates through every character, the other iterates through every character in every independent realm. Ultimately they are both iterating through every character.

I'm just curious how one could possibly be less expensive.

**Comment by Whizzer** [comment]
If I understand it correctly, the first one fired the event for every character, the fix filters first and only fires the event for eligible characters. Not firing thousands of additional events has to make a difference.

**Comment by questionmarkexclamationpoint** [comment]
Hmm, OK. Can you get the same thing out of:
```
immediate = {
    any_character = {
        limit = { age < 2 }
        character_event = { PlusMaintenance.003 }
    }
}
```

**Comment by Whizzer** [comment]
Should work, yes.

**Comment by schwarherz** [comment]
As I understand it, the difference is how the engine processes it. `any_character = {}` does all of the logic at once. `any_independent_ruler = { any_realm_character = { } }` is processed in stages. So the engine will select each independent ruler individually, then all of their subjects and fire the event for them. It, basically, breaks the processing into easier to digest chunks.

**Pull request merged**
