### PR TITLE
remove province histories from vanilla that should have been deleted …

### PR DESCRIPTION
**Pull request by questionmarkexclamationpoint**
…by paradox

These are province history files that *are in vanilla* which refer to provinces whose ids were re-purposed for other provinces *in vanilla*. That is, Paradox simply neglected to delete some province histories that they should have.

I'm deleting them from our repo because they are not used by the game.

### CODE REVIEW

**Comment by questionmarkexclamationpoint** [comment]
No, the files that were deleted were either merged into other provinces or renamed.

**Comment by questionmarkexclamationpoint** [comment]
One example is that Droutsk got renamed to Drutsk.

**Comment by schwarherz** [comment]
If you add an override declaration to the extended's .mod file I'll be happy to merge this then (there are examples in the old repo's .mod files)

**Comment by questionmarkexclamationpoint** [comment]
Closing for now so I can re-copy province history as mentioned in #106.

**Pull request closed without merging**
